name: UnlimitedMagicalBook
author: '１５４１２'
main: org.c15412.Plugin3.MainClass
version: 'test.000.0213'
api-version: '1.16'

permissions:
  UMB.*:
    children:
      UMB.USE: true
  UMB.USE:
    description: '允许玩家使用卷轴'
    default: true

commands: